"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#076678" }

# Find
find_keyword  = { fg = "#79740e", bold = true, italic = true, underline = true }
find_position = { fg = "#8f3f71", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#689d6a", bg = "#689d6a" }
marker_cut      = { fg = "#cc241d", bg = "#cc241d" }
marker_marked   = { fg = "#458588", bg = "#458588" }
marker_selected = { fg = "#d79921", bg = "#d79921" }

# Count
count_copied   = { fg = "#f9f5d7", bg = "#689d6a" }
count_cut      = { fg = "#f9f5d7", bg = "#cc241d" }
count_selected = { fg = "#f9f5d7", bg = "#d79921" }

# Border
border_symbol = "|"
border_style  = { fg = "#bdae93" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#f9f5d7", bg = "#665c54", bold = true }
inactive = { fg = "#665c54", bg = "#d5c4a1" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#f9f5d7", bg = "#665c54", bold = true }
normal_alt  = { fg = "#665c54", bg = "#d5c4a1" }

# Select mode
select_main = { fg = "#f9f5d7", bg = "#d65d0e", bold = true }
select_alt  = { fg = "#665c54", bg = "#d5c4a1" }

# Unset mode
unset_main = { fg = "#f9f5d7", bg = "#98971a", bold = true }
unset_alt  = { fg = "#665c54", bg = "#d5c4a1" }

# : }}}


# : Indicator of hovered file {{{

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "#", close = "#" }

# : }}}


# : Status {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#bdae93" }
perm_type  = { fg = "#504945" }
perm_read  = { fg = "#79740e" }
perm_write = { fg = "#9d0006" }
perm_exec  = { fg = "#076678" }

# Progress
progress_label  = { fg = "#3c3836", bold = true }
progress_normal = { fg = "#504945", bg = "#ebdbb2" }
progress_error  = { fg = "#9d0006", bg = "#ebdbb2" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#ebdbb2" }
cand            = { fg = "#458588" }
rest            = { fg = "#928374" }
desc            = { fg = "#d65d0e" }
separator       = " -> "
separator_style = { fg = "#a89984" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#665c54" }
title      = { fg = "#076678" }
body       = { fg = "#3c3836" }
list       = { fg = "#504945" }
btn_yes    = { reversed = true, fg = "#3c3836" }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#076678" }
title  = { fg = "#076678" }

# Table
tbl_col  = { fg = "#076678" }
tbl_cell = { fg = "#b57614", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#689d6a" }
title_warn  = { fg = "#d79921" }
title_error = { fg = "#cc241d" }

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#458588" }
active   = { fg = "#b16286", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#3c3836" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#665c54" }
active   = { reversed = true, fg = "#076678" }
inactive = { fg = "#3c3836" }

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#d5c4a1" }
title   = {}
hovered = { underline = true }

# : }}}


# : Help {{{

[help]
on      = { fg = "#076678" }
run     = { fg = "#b16286" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#f9f5d7", bg = "#665c54" }

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b16286" },

  # Media
  { mime = "{audio,video}/*", fg = "#d79921" },

  # Archives
  { mime = "application/*zip", fg = "#cc241d" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#cc241d" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#689d6a" },

  # Fallback
  { url = "*", fg = "#3c3836" },
  { url = "*/", fg = "#458588" },
]

# : }}}
